### ISSUE TITLE
 numpy has no attribute int

### ISSUE THREAD

**Issue by zjans** [tretherington/nlmpy#8]
Hi,

running the model with NumPy version >1.20 leads to the following Error

```*** AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

This can be easily fixed by changing line 534 in nlmpy.py from:

```N = np.int(np.ceil(np.log2(maxDim - 1)))```

to:

```N = np.ceil(np.log2(maxDim - 1)).astype(int)```

**Comment by tretherington** [comment]
Thanks for pointing this out.  Having checked this is the only instance of this, and have updated following the NumPy advice to:

`N = int(np.ceil(np.log2(maxDim - 1)))`

which seems the safest to me for backwards compatibility.

I'll create a new release on PyPI tomorrow.

**Comment by tretherington** [comment]
Version 1.1.2 now on PyPi
